# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import query_pb2 as query__pb2


class QueryStub(object):
  """Service provided by the workers that the master can talk to.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryOnline = channel.unary_unary(
        '/infaas.internal.Query/QueryOnline',
        request_serializer=query__pb2.QueryOnlineRequest.SerializeToString,
        response_deserializer=query__pb2.QueryOnlineResponse.FromString,
        )
    self.QueryOffline = channel.unary_unary(
        '/infaas.internal.Query/QueryOffline',
        request_serializer=query__pb2.QueryOfflineRequest.SerializeToString,
        response_deserializer=query__pb2.QueryOfflineResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/infaas.internal.Query/Heartbeat',
        request_serializer=query__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=query__pb2.HeartbeatResponse.FromString,
        )


class QueryServicer(object):
  """Service provided by the workers that the master can talk to.
  """

  def QueryOnline(self, request, context):
    """Online query, send input data in the payload
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryOffline(self, request, context):
    """Offline query, input data are stored on the cloud
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    """Heartbeat
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryOnline': grpc.unary_unary_rpc_method_handler(
          servicer.QueryOnline,
          request_deserializer=query__pb2.QueryOnlineRequest.FromString,
          response_serializer=query__pb2.QueryOnlineResponse.SerializeToString,
      ),
      'QueryOffline': grpc.unary_unary_rpc_method_handler(
          servicer.QueryOffline,
          request_deserializer=query__pb2.QueryOfflineRequest.FromString,
          response_serializer=query__pb2.QueryOfflineResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=query__pb2.HeartbeatRequest.FromString,
          response_serializer=query__pb2.HeartbeatResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'infaas.internal.Query', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
