# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import infaas_request_status_pb2 as infaas__request__status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='infaas.internal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bquery.proto\x12\x0finfaas.internal\x1a\x1binfaas_request_status.proto\"G\n\x08QuerySLO\x12\x15\n\rLatencyInUSec\x18\x01 \x01(\x03\x12\x13\n\x0bMinAccuracy\x18\x02 \x01(\x02\x12\x0f\n\x07MaxCost\x18\x03 \x01(\x02\"q\n\x12QueryOnlineRequest\x12\x11\n\traw_input\x18\x01 \x03(\x0c\x12\r\n\x05model\x18\x02 \x03(\t\x12&\n\x03slo\x18\x03 \x01(\x0b\x32\x19.infaas.internal.QuerySLO\x12\x11\n\tsubmitter\x18\x04 \x01(\t\"_\n\x13QueryOnlineResponse\x12\x12\n\nraw_output\x18\x01 \x03(\x0c\x12\x34\n\x06status\x18\x02 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"\x86\x01\n\x13QueryOfflineRequest\x12\x11\n\tinput_url\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x03(\t\x12\x12\n\noutput_url\x18\x03 \x01(\t\x12&\n\x03slo\x18\x04 \x01(\x0b\x32\x19.infaas.internal.QuerySLO\x12\x11\n\tsubmitter\x18\x05 \x01(\t\"L\n\x14QueryOfflineResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"H\n\x10HeartbeatRequest\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"I\n\x11HeartbeatResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus2\x98\x02\n\x05Query\x12Z\n\x0bQueryOnline\x12#.infaas.internal.QueryOnlineRequest\x1a$.infaas.internal.QueryOnlineResponse\"\x00\x12]\n\x0cQueryOffline\x12$.infaas.internal.QueryOfflineRequest\x1a%.infaas.internal.QueryOfflineResponse\"\x00\x12T\n\tHeartbeat\x12!.infaas.internal.HeartbeatRequest\x1a\".infaas.internal.HeartbeatResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[infaas__request__status__pb2.DESCRIPTOR,])




_QUERYSLO = _descriptor.Descriptor(
  name='QuerySLO',
  full_name='infaas.internal.QuerySLO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LatencyInUSec', full_name='infaas.internal.QuerySLO.LatencyInUSec', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MinAccuracy', full_name='infaas.internal.QuerySLO.MinAccuracy', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxCost', full_name='infaas.internal.QuerySLO.MaxCost', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=132,
)


_QUERYONLINEREQUEST = _descriptor.Descriptor(
  name='QueryOnlineRequest',
  full_name='infaas.internal.QueryOnlineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_input', full_name='infaas.internal.QueryOnlineRequest.raw_input', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='infaas.internal.QueryOnlineRequest.model', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slo', full_name='infaas.internal.QueryOnlineRequest.slo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='submitter', full_name='infaas.internal.QueryOnlineRequest.submitter', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=247,
)


_QUERYONLINERESPONSE = _descriptor.Descriptor(
  name='QueryOnlineResponse',
  full_name='infaas.internal.QueryOnlineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_output', full_name='infaas.internal.QueryOnlineResponse.raw_output', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='infaas.internal.QueryOnlineResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=344,
)


_QUERYOFFLINEREQUEST = _descriptor.Descriptor(
  name='QueryOfflineRequest',
  full_name='infaas.internal.QueryOfflineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_url', full_name='infaas.internal.QueryOfflineRequest.input_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='infaas.internal.QueryOfflineRequest.model', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_url', full_name='infaas.internal.QueryOfflineRequest.output_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slo', full_name='infaas.internal.QueryOfflineRequest.slo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='submitter', full_name='infaas.internal.QueryOfflineRequest.submitter', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=481,
)


_QUERYOFFLINERESPONSE = _descriptor.Descriptor(
  name='QueryOfflineResponse',
  full_name='infaas.internal.QueryOfflineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='infaas.internal.QueryOfflineResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=559,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='infaas.internal.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='infaas.internal.HeartbeatRequest.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=633,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='infaas.internal.HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='infaas.internal.HeartbeatResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=708,
)

_QUERYONLINEREQUEST.fields_by_name['slo'].message_type = _QUERYSLO
_QUERYONLINERESPONSE.fields_by_name['status'].message_type = infaas__request__status__pb2._INFAASREQUESTSTATUS
_QUERYOFFLINEREQUEST.fields_by_name['slo'].message_type = _QUERYSLO
_QUERYOFFLINERESPONSE.fields_by_name['status'].message_type = infaas__request__status__pb2._INFAASREQUESTSTATUS
_HEARTBEATREQUEST.fields_by_name['status'].message_type = infaas__request__status__pb2._INFAASREQUESTSTATUS
_HEARTBEATRESPONSE.fields_by_name['status'].message_type = infaas__request__status__pb2._INFAASREQUESTSTATUS
DESCRIPTOR.message_types_by_name['QuerySLO'] = _QUERYSLO
DESCRIPTOR.message_types_by_name['QueryOnlineRequest'] = _QUERYONLINEREQUEST
DESCRIPTOR.message_types_by_name['QueryOnlineResponse'] = _QUERYONLINERESPONSE
DESCRIPTOR.message_types_by_name['QueryOfflineRequest'] = _QUERYOFFLINEREQUEST
DESCRIPTOR.message_types_by_name['QueryOfflineResponse'] = _QUERYOFFLINERESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuerySLO = _reflection.GeneratedProtocolMessageType('QuerySLO', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSLO,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QuerySLO)
  ))
_sym_db.RegisterMessage(QuerySLO)

QueryOnlineRequest = _reflection.GeneratedProtocolMessageType('QueryOnlineRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYONLINEREQUEST,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOnlineRequest)
  ))
_sym_db.RegisterMessage(QueryOnlineRequest)

QueryOnlineResponse = _reflection.GeneratedProtocolMessageType('QueryOnlineResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYONLINERESPONSE,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOnlineResponse)
  ))
_sym_db.RegisterMessage(QueryOnlineResponse)

QueryOfflineRequest = _reflection.GeneratedProtocolMessageType('QueryOfflineRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYOFFLINEREQUEST,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOfflineRequest)
  ))
_sym_db.RegisterMessage(QueryOfflineRequest)

QueryOfflineResponse = _reflection.GeneratedProtocolMessageType('QueryOfflineResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYOFFLINERESPONSE,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOfflineResponse)
  ))
_sym_db.RegisterMessage(QueryOfflineResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATREQUEST,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.HeartbeatRequest)
  ))
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATRESPONSE,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.HeartbeatResponse)
  ))
_sym_db.RegisterMessage(HeartbeatResponse)



_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='infaas.internal.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=711,
  serialized_end=991,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryOnline',
    full_name='infaas.internal.Query.QueryOnline',
    index=0,
    containing_service=None,
    input_type=_QUERYONLINEREQUEST,
    output_type=_QUERYONLINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryOffline',
    full_name='infaas.internal.Query.QueryOffline',
    index=1,
    containing_service=None,
    input_type=_QUERYOFFLINEREQUEST,
    output_type=_QUERYOFFLINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='infaas.internal.Query.Heartbeat',
    index=2,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
